// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema/bid/bid.proto

package bid_bid

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OutStatus int32

const (
	OutStatus_UNKNOW     OutStatus = 0
	OutStatus_OK         OutStatus = 1
	OutStatus_VALIDATION OutStatus = 2
	OutStatus_ERROR      OutStatus = 3
)

var OutStatus_name = map[int32]string{
	0: "UNKNOW",
	1: "OK",
	2: "VALIDATION",
	3: "ERROR",
}

var OutStatus_value = map[string]int32{
	"UNKNOW":     0,
	"OK":         1,
	"VALIDATION": 2,
	"ERROR":      3,
}

func (x OutStatus) String() string {
	return proto.EnumName(OutStatus_name, int32(x))
}

func (OutStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_317da216e33c9850, []int{0}
}

type OutHeader struct {
	Status               OutStatus `protobuf:"varint,1,opt,name=status,proto3,enum=bid.bid.OutStatus" json:"status,omitempty"`
	Message              string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *OutHeader) Reset()         { *m = OutHeader{} }
func (m *OutHeader) String() string { return proto.CompactTextString(m) }
func (*OutHeader) ProtoMessage()    {}
func (*OutHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_317da216e33c9850, []int{0}
}

func (m *OutHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutHeader.Unmarshal(m, b)
}
func (m *OutHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutHeader.Marshal(b, m, deterministic)
}
func (m *OutHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutHeader.Merge(m, src)
}
func (m *OutHeader) XXX_Size() int {
	return xxx_messageInfo_OutHeader.Size(m)
}
func (m *OutHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_OutHeader.DiscardUnknown(m)
}

var xxx_messageInfo_OutHeader proto.InternalMessageInfo

func (m *OutHeader) GetStatus() OutStatus {
	if m != nil {
		return m.Status
	}
	return OutStatus_UNKNOW
}

func (m *OutHeader) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// Create
type CreateIn struct {
	CoinType             uint64   `protobuf:"varint,1,opt,name=coinType,proto3" json:"coinType,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateIn) Reset()         { *m = CreateIn{} }
func (m *CreateIn) String() string { return proto.CompactTextString(m) }
func (*CreateIn) ProtoMessage()    {}
func (*CreateIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_317da216e33c9850, []int{1}
}

func (m *CreateIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateIn.Unmarshal(m, b)
}
func (m *CreateIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateIn.Marshal(b, m, deterministic)
}
func (m *CreateIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateIn.Merge(m, src)
}
func (m *CreateIn) XXX_Size() int {
	return xxx_messageInfo_CreateIn.Size(m)
}
func (m *CreateIn) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateIn.DiscardUnknown(m)
}

var xxx_messageInfo_CreateIn proto.InternalMessageInfo

func (m *CreateIn) GetCoinType() uint64 {
	if m != nil {
		return m.CoinType
	}
	return 0
}

func (m *CreateIn) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *CreateIn) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type CreateOut struct {
	Header               *OutHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Id                   string     `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateOut) Reset()         { *m = CreateOut{} }
func (m *CreateOut) String() string { return proto.CompactTextString(m) }
func (*CreateOut) ProtoMessage()    {}
func (*CreateOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_317da216e33c9850, []int{2}
}

func (m *CreateOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOut.Unmarshal(m, b)
}
func (m *CreateOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOut.Marshal(b, m, deterministic)
}
func (m *CreateOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOut.Merge(m, src)
}
func (m *CreateOut) XXX_Size() int {
	return xxx_messageInfo_CreateOut.Size(m)
}
func (m *CreateOut) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOut.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOut proto.InternalMessageInfo

func (m *CreateOut) GetHeader() *OutHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *CreateOut) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Get
type GetIn struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIn) Reset()         { *m = GetIn{} }
func (m *GetIn) String() string { return proto.CompactTextString(m) }
func (*GetIn) ProtoMessage()    {}
func (*GetIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_317da216e33c9850, []int{3}
}

func (m *GetIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIn.Unmarshal(m, b)
}
func (m *GetIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIn.Marshal(b, m, deterministic)
}
func (m *GetIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIn.Merge(m, src)
}
func (m *GetIn) XXX_Size() int {
	return xxx_messageInfo_GetIn.Size(m)
}
func (m *GetIn) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIn.DiscardUnknown(m)
}

var xxx_messageInfo_GetIn proto.InternalMessageInfo

func (m *GetIn) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetOut struct {
	Header               *OutHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Status               uint64     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	ReceivedCoinType     uint64     `protobuf:"varint,3,opt,name=receivedCoinType,proto3" json:"receivedCoinType,omitempty"`
	ReceivedValue        string     `protobuf:"bytes,4,opt,name=receivedValue,proto3" json:"receivedValue,omitempty"`
	ReceivedAddress      string     `protobuf:"bytes,5,opt,name=receivedAddress,proto3" json:"receivedAddress,omitempty"`
	GivenCoinType        uint64     `protobuf:"varint,6,opt,name=givenCoinType,proto3" json:"givenCoinType,omitempty"`
	GivenValue           string     `protobuf:"bytes,7,opt,name=givenValue,proto3" json:"givenValue,omitempty"`
	GivenAddress         string     `protobuf:"bytes,8,opt,name=givenAddress,proto3" json:"givenAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetOut) Reset()         { *m = GetOut{} }
func (m *GetOut) String() string { return proto.CompactTextString(m) }
func (*GetOut) ProtoMessage()    {}
func (*GetOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_317da216e33c9850, []int{4}
}

func (m *GetOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOut.Unmarshal(m, b)
}
func (m *GetOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOut.Marshal(b, m, deterministic)
}
func (m *GetOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOut.Merge(m, src)
}
func (m *GetOut) XXX_Size() int {
	return xxx_messageInfo_GetOut.Size(m)
}
func (m *GetOut) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOut.DiscardUnknown(m)
}

var xxx_messageInfo_GetOut proto.InternalMessageInfo

func (m *GetOut) GetHeader() *OutHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetOut) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetOut) GetReceivedCoinType() uint64 {
	if m != nil {
		return m.ReceivedCoinType
	}
	return 0
}

func (m *GetOut) GetReceivedValue() string {
	if m != nil {
		return m.ReceivedValue
	}
	return ""
}

func (m *GetOut) GetReceivedAddress() string {
	if m != nil {
		return m.ReceivedAddress
	}
	return ""
}

func (m *GetOut) GetGivenCoinType() uint64 {
	if m != nil {
		return m.GivenCoinType
	}
	return 0
}

func (m *GetOut) GetGivenValue() string {
	if m != nil {
		return m.GivenValue
	}
	return ""
}

func (m *GetOut) GetGivenAddress() string {
	if m != nil {
		return m.GivenAddress
	}
	return ""
}

func init() {
	proto.RegisterEnum("bid.bid.OutStatus", OutStatus_name, OutStatus_value)
	proto.RegisterType((*OutHeader)(nil), "bid.bid.OutHeader")
	proto.RegisterType((*CreateIn)(nil), "bid.bid.CreateIn")
	proto.RegisterType((*CreateOut)(nil), "bid.bid.CreateOut")
	proto.RegisterType((*GetIn)(nil), "bid.bid.GetIn")
	proto.RegisterType((*GetOut)(nil), "bid.bid.GetOut")
}

func init() {
	proto.RegisterFile("schema/bid/bid.proto", fileDescriptor_317da216e33c9850)
}

var fileDescriptor_317da216e33c9850 = []byte{
	// 405 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xc1, 0x6e, 0x9b, 0x40,
	0x10, 0x0d, 0x10, 0xb0, 0x99, 0xb6, 0x84, 0x8e, 0xa2, 0x16, 0xf9, 0x50, 0x45, 0xa8, 0x07, 0xe4,
	0x83, 0xab, 0xa6, 0xb7, 0xde, 0xdc, 0xb4, 0xa2, 0x28, 0x95, 0x57, 0xa5, 0xa9, 0x7b, 0x06, 0xef,
	0x28, 0x59, 0xa9, 0xc1, 0x11, 0x2c, 0x96, 0xfa, 0x5b, 0xfd, 0xc2, 0x8a, 0x81, 0x45, 0xc1, 0x3d,
	0xe5, 0x80, 0xc4, 0x7b, 0xf3, 0xf6, 0xcd, 0xec, 0xdb, 0x81, 0xf3, 0x66, 0x77, 0x47, 0xf7, 0xc5,
	0xbb, 0x52, 0xc9, 0xee, 0x5b, 0x3d, 0xd4, 0x7b, 0xbd, 0xc7, 0x59, 0xf7, 0x5b, 0x2a, 0x19, 0x7f,
	0x07, 0x5f, 0xb4, 0xfa, 0x2b, 0x15, 0x92, 0x6a, 0x5c, 0x82, 0xd7, 0xe8, 0x42, 0xb7, 0x4d, 0x64,
	0x5d, 0x58, 0x49, 0x70, 0x89, 0xab, 0x41, 0xb6, 0x12, 0xad, 0xfe, 0xc1, 0x95, 0x7c, 0x50, 0x60,
	0x04, 0xb3, 0x7b, 0x6a, 0x9a, 0xe2, 0x96, 0x22, 0xfb, 0xc2, 0x4a, 0xfc, 0xdc, 0xc0, 0x78, 0x0b,
	0xf3, 0xab, 0x9a, 0x0a, 0x4d, 0x59, 0x85, 0x0b, 0x98, 0xef, 0xf6, 0xaa, 0xba, 0xf9, 0xf3, 0x40,
	0xec, 0x79, 0x9a, 0x8f, 0x18, 0xcf, 0xc1, 0x3d, 0x14, 0xbf, 0x5b, 0x73, 0xbe, 0x07, 0x9d, 0x6f,
	0x21, 0x65, 0x4d, 0x4d, 0x13, 0x39, 0xbd, 0xef, 0x00, 0xe3, 0x14, 0xfc, 0xde, 0x57, 0xb4, 0xba,
	0x1b, 0xf5, 0x8e, 0x87, 0x66, 0xdb, 0x67, 0xd3, 0x51, 0xfb, 0xeb, 0xe4, 0x83, 0x02, 0x03, 0xb0,
	0x95, 0x1c, 0xba, 0xd8, 0x4a, 0xc6, 0xaf, 0xc1, 0x4d, 0x49, 0x67, 0xd5, 0x50, 0xb0, 0xc6, 0xc2,
	0x5f, 0x1b, 0xbc, 0x94, 0xf4, 0x53, 0xfd, 0x5f, 0x8d, 0xb1, 0xd9, 0x7c, 0x45, 0x13, 0xd1, 0x12,
	0xc2, 0x9a, 0x76, 0xa4, 0x0e, 0x24, 0xaf, 0x4c, 0x08, 0x0e, 0x2b, 0xfe, 0xe3, 0xf1, 0x2d, 0xbc,
	0x30, 0xdc, 0x96, 0x43, 0x39, 0xe5, 0xa9, 0xa6, 0x24, 0x26, 0x70, 0x66, 0x88, 0xf5, 0x10, 0x92,
	0xcb, 0xba, 0x63, 0xba, 0xf3, 0xbb, 0x55, 0x07, 0xaa, 0xc6, 0xc6, 0x1e, 0x37, 0x9e, 0x92, 0xf8,
	0x06, 0x80, 0x89, 0xbe, 0xe5, 0x8c, 0xad, 0x1e, 0x31, 0x18, 0xc3, 0x73, 0x46, 0xa6, 0xd9, 0x9c,
	0x15, 0x13, 0x6e, 0xf9, 0x91, 0x37, 0xa8, 0xdf, 0x0e, 0x04, 0xf0, 0x7e, 0x6e, 0xae, 0x37, 0xe2,
	0x57, 0x78, 0x82, 0x1e, 0xd8, 0xe2, 0x3a, 0xb4, 0x30, 0x00, 0xd8, 0xae, 0xbf, 0x65, 0x9f, 0xd7,
	0x37, 0x99, 0xd8, 0x84, 0x36, 0xfa, 0xe0, 0x7e, 0xc9, 0x73, 0x91, 0x87, 0xce, 0x65, 0x09, 0xce,
	0x27, 0x25, 0xf1, 0x3d, 0x78, 0xfd, 0xcb, 0xe2, 0xcb, 0x31, 0x66, 0xb3, 0x42, 0x0b, 0x3c, 0xa2,
	0x44, 0xab, 0xe3, 0x13, 0x4c, 0xc0, 0x49, 0x49, 0x63, 0x30, 0x16, 0xf9, 0x45, 0x17, 0x67, 0x8f,
	0x31, 0x2b, 0x4b, 0x8f, 0x37, 0xfe, 0xc3, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x59, 0xcb, 0x6d,
	0x42, 0x09, 0x03, 0x00, 0x00,
}
