version: "3"

networks:
  nats:
    driver: bridge
  postgres:
    driver: bridge
  btc:
    driver: bridge
  eth:
    driver: bridge
  nginx:
    driver: bridge
  apache:
    driver: bridge
  gateway:
    driver: bridge
  mysql:
    driver: bridge

volumes:
  site: {}

services:
  gateway:
    build:
      context: .
      dockerfile: build/package/gateway/Dockerfile
    depends_on:
      - nats
      - bid
    restart: on-failure
    ports:
      - "6080:6080"
    expose:
      - 6080
    environment:
      MICRO_REGISTRYADDRESS: "nats:4222"
      MICRO_BROKERADDRESS: "nats:4222"
      MICRO_TRANSPORTADDRESS: "nats:4222"

      HTTP_HOST: "0.0.0.0"
      HTTP_PORT: 6080
    volumes:
      - /var/log/otus_arch_project/:/var/log/gateway/
    networks:
      - nats
      - gateway

  bid:
    build:
      context: .
      dockerfile: build/package/bid/Dockerfile
    depends_on:
      - nats
      - postgres
      - bitcoin
      - ethereum
    restart: on-failure
    environment:
      MICRO_REGISTRYADDRESS: "nats:4222"
      MICRO_BROKERADDRESS: "nats:4222"
      MICRO_TRANSPORTADDRESS: "nats:4222"

      DATABASE_DSN: "host=postgres port=5432 password=bid123 user=bid dbname=bid sslmode=disable"

      NODES_BTC_HOST: "bitcoin"
      NODES_BTC_PORT: 18332
      NODES_BTC_USER: "btcuser"
      NODES_BTC_PASS: "btcpass123"

      NODES_ETH_HOST: "ethereum"
      NODES_ETH_PORT: 8545
    volumes:
      - /var/log/otus_arch_project/:/var/log/bid/
    networks:
      - nats
      - postgres
      - btc
      - eth

  pending:
    build:
      context: .
      dockerfile: build/package/pending/Dockerfile
    depends_on:
      - postgres
      - bitcoin
      - ethereum
    restart: on-failure
    environment:
      DATABASE_DSN: "host=postgres port=5432 password=bid123 user=bid dbname=bid sslmode=disable"

      NODES_BTC_HOST: "bitcoin"
      NODES_BTC_PORT: 18332
      NODES_BTC_USER: "btcuser"
      NODES_BTC_PASS: "btcpass123"

      NODES_ETH_HOST: "ethereum"
      NODES_ETH_PORT: 8545
    volumes:
      - /var/log/otus_arch_project/:/var/log/pending/
    networks:
      - postgres
      - btc
      - eth

  goose:
    build:
      context: .
      dockerfile: build/package/goose/Dockerfile
    depends_on:
      - postgres
    restart: on-failure
    environment:
      GOOSE_DRIVER: "postgres"
      GOOSE_DBSTRING: "host=postgres port=5432 password=bid123 user=bid dbname=bid sslmode=disable"
    networks:
      - postgres

  bitcoin:
    build:
      context: .
      dockerfile: build/package/bitcoin/Dockerfile
    restart: on-failure
    ports:
      - "58332:18332"
    expose:
      - 58332
    volumes:
      - .bitcoin/bitcoin:/bitcoin/.bitcoin/bitcoin
    networks:
      - btc

  ethereum:
    build:
      context: .
      dockerfile: build/package/ethereum/Dockerfile
    restart: on-failure
    ports:
      - "58545:8545"
    expose:
      - 58545
    volumes:
      - .ethereum:/root/.ethereum
    networks:
      - eth

  postgres:
    image: postgres:11-alpine
    ports:
      - "55432:5432"
    expose:
      - 55432
    environment:
      POSTGRES_USER: bid
      POSTGRES_PASSWORD: bid123
      POSTGRES_DB: bid
    networks:
      - postgres

  nats:
    image: nats:2.1.9-alpine3.12
    ports:
      - "54222:4222" # is for clients.
      - "56222:6222" # is an HTTP management port for information reporting.
      - "58222:8222" # is a routing port for clustering.
    expose:
      - 54222
      - 56222
    networks:
      - nats

  nginx:
    build:
      context: .
      dockerfile: build/package/nginx/Dockerfile
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 80
      - 443
    volumes:
      - site:/var/www/html
      - /var/log/otus_arch_project/nginx:/var/log/nginx
    networks:
      - nginx
      - apache

  apache:
    build:
      context: .
      dockerfile: build/package/apache/Dockerfile
    restart: on-failure
    ports:
      - "58080:80"
    expose:
      - 58080
    volumes:
      - site:/var/www/html
      - /var/log/otus_arch_project/apache2:/var/log/apache2
    depends_on:
      - mysql
    networks:
      - apache
      - mysql
      - gateway

  mysql:
    image: mysql:5.7
    ports:
      - "53306:3306"
    expose:
      - 53306
    environment:
      - MYSQL_ROOT_PASSWORD=Qybf0H8aQ0
      - MYSQL_DATABASE=otus_arch_project
    networks:
      - mysql
