app:
  name: "bid.service"

micro:
  registry: "nats"
  registryAddress: "0.0.0.0:34222"

  broker: "nats"
  brokerAddress: "0.0.0.0:34222"

  transport: "nats"
  transportAddress: "0.0.0.0:34222"

logging:
  file: "./bid.log"
  level: "debug"

database:
  dsn: "host=127.0.0.1 port=5432 password=bid123 user=bid dbname=bid sslmode=disable"

addresses:
  # ETH wallet
  1: "0x4e0dd25162ff410c3c16dbee3946c14def3643d8"

  # BTC wallet
  2: "2NG4HS1dRdJDrZpkKZRZww1ktPGjvfUsVS1"

fee: 5

nodes:
  BTC:
    Host: "0.0.0.0"
    Port: 18332
    User: "btcuser"
    Pass: "btcpass123"
  ETH:
    Host: "0.0.0.0"
    Port: 8545